### ISSUE TITLE
Reference to the paper

### ISSUE THREAD

**Issue by ujasmandavia** [dzunigan/imu_initializaiton#1]
This is a great implementation, but I cannot find the similar paper mentioned and I am assuming this IMU initialization is similar to one mentioned in ORB SLAM 3 where they are talking about Inertial only optimization and also some reference from Visual Inertial monocular SLAM with map reuse

**Comment by dzunigan** [comment]
The draft is now available through arXiv, check the readme.
Thanks for your interest!
