### ISSUE TITLE
Whether your method can deal with pure rotational motion or non-accelerated motions

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [dzunigan/imu_initializaiton#4]
Thank you for your excellent work!I would like to ask you whether the method you proposed is applicable to the VIO initialization process when the vehicle is moving at uniform speed or in a straight line?

**Comment by dzunigan** [comment]
The IMU initialization problem is not observable from constant velocity motion. In case of moving in a single direction (straight line), only the accelerometer bias is not observable. I think the proposed method should work fine with a prior for the accelerometer bias, but I didn't tested it out.
